### PR TITLE
responsiveness fix on right banner decor

### LINKED ISSUE #63: Responsive Banner Text
image

### PR DESCRIPTION
**Pull request by aviamb**
small screen: 
image

medium screen:
image

large screen: 
image

fixes #63

### CODE REVIEW

File: src/components/Banner.jsx [hunk 1]
```diff
@@ -16,7 +16,7 @@ const Banner = ({ text }) => {
       <div className="absolute start-0 end-0 inset-y-2/3 pr-4">
         <Image src={BannerDecor1} alt="Banner Decor 1" className="w-1/6" />
       </div>
-      <div className="absolute end-0 inset-y-2/3 w-1/5">
+      <div className="absolute w-1/6 -bottom-7 md:-bottom-10 lg:-bottom-20 right-0">
```
Comment (SafeDuck) [inline src/components/Banner.jsx]: This is good, however can you also center the text

**Review by SafeDuck — CHANGES_REQUESTED** [review]

**Comment by aviamb** [comment]
let me know if this is good, or i can make more edits :)

lg: 
image
 
md: 
image

sm: 
image

**Review by SafeDuck — APPROVED** [review]
